/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:6b8df3f3-a0f9-4b17-88d1-5ea4a4cd25b8",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_XJrEo2VJG",
    "aws_user_pools_web_client_id": "2ps20huk5nt3oujurjgbsba1m",
    "oauth": {}
};


export default awsmobile;
